// src/constants/images.js
const images = {
    egg: require('../assets/images/ingredients/egg.jpg'),
    apple: require('../assets/images/ingredients/apple.jpg'),
    chicken: require('../assets/images/ingredients/chicken.jpg'),
    flour: require('../assets/images/ingredients/flour.jpg'),
    butter: require('../assets/images/ingredients/butter.jpg'),
    milk: require('../assets/images/ingredients/milk.jpg'),
    garlic: require('../assets/images/ingredients/garlic.jpg'),
    onion: require('../assets/images/ingredients/onion.jpg'),
    tomato: require('../assets/images/ingredients/tomato.jpg'),
    rice: require('../assets/images/ingredients/rice.jpg'),
    bread: require('../assets/images/ingredients/bread.jpg'),
    cheese: require('../assets/images/ingredients/cheese.jpg'),
    carrot: require('../assets/images/ingredients/carrot.jpg'),
    potato: require('../assets/images/ingredients/potato.jpg'),
    lemon: require('../assets/images/ingredients/lemon.jpg'),
    beef: require('../assets/images/ingredients/beef.jpg'),
    bacon: require('../assets/images/ingredients/bacon.jpg'),
    honey: require('../assets/images/ingredients/honey.jpg'),
    spinach: require('../assets/images/ingredients/spinach.jpg'),
    broccoli: require('../assets/images/ingredients/broccoli.jpg'),
    bellpepper: require('../assets/images/ingredients/bellpepper.jpg'),
    mushroom: require('../assets/images/ingredients/mushroom.jpg'),
    basil: require('../assets/images/ingredients/basil.jpg'),
    parsley: require('../assets/images/ingredients/parsley.jpg'),
    pork: require('../assets/images/ingredients/pork.jpg'),
    shrimp: require('../assets/images/ingredients/shrimp.jpg'),
    coconutmilk: require('../assets/images/ingredients/coconutmilk.jpg'),
    cucumber: require('../assets/images/ingredients/cucumber.jpg'),
    strawberry: require('../assets/images/ingredients/strawberry.jpg'),
    blueberry: require('../assets/images/ingredients/blueberry.jpg'),
    banana: require('../assets/images/ingredients/banana.jpg'),
    raspberry: require('../assets/images/ingredients/raspberry.jpg'),
    cilantro: require('../assets/images/ingredients/cilantro.jpg'),
    corn: require('../assets/images/ingredients/corn.jpg'),
    lettuce: require('../assets/images/ingredients/lettuce.jpg'),
    chili: require('../assets/images/ingredients/chili.jpg'),
    yogurt: require('../assets/images/ingredients/yogurt.jpg'),
    avocado: require('../assets/images/ingredients/avocado.jpg'),
    fish: require('../assets/images/ingredients/fish.jpg'),
    salmon: require('../assets/images/ingredients/salmon.jpg'),
    kale: require('../assets/images/ingredients/kale.jpg'),
    lime: require('../assets/images/ingredients/lime.jpg'),
    creamcheese: require('../assets/images/ingredients/creamcheese.jpg'),
    zucchini: require('../assets/images/ingredients/zucchini.jpg'),
    pasta: require('../assets/images/ingredients/pasta.jpg'),
    pesto: require('../assets/images/ingredients/pesto.jpg'),
    mint: require('../assets/images/ingredients/mint.jpg'),
    ginger: require('../assets/images/ingredients/ginger.jpg'),
    asparagus: require('../assets/images/ingredients/asparagus.jpg'),
    tofu: require('../assets/images/ingredients/tofu.jpg'),
    orange: require('../assets/images/ingredients/orange.jpg'),
    sausage: require('../assets/images/ingredients/sausage.jpg'),
    greenonion: require('../assets/images/ingredients/greenonion.jpg'),
    sweetpotato: require('../assets/images/ingredients/sweetpotato.jpg'),
    quinoa: require('../assets/images/ingredients/quinoa.jpg'),
    cabbage: require('../assets/images/ingredients/cabbage.jpg'),
    rosemary: require('../assets/images/ingredients/rosemary.jpg'),
    turkey: require('../assets/images/ingredients/turkey.jpg'),
    pumpkin: require('../assets/images/ingredients/pumpkin.jpg'),
    chickpeas: require('../assets/images/ingredients/chickpeas.jpg'),
    tomatosauce: require('../assets/images/ingredients/tomatosauce.jpg'),
  };
  
  // Export the images object
  export default images;
  