# This action works with pull requests and pushes
name: Auto pep8

on:
  pull_request:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      options: --user 1001
    steps:
    - uses: actions/checkout@v3
      with:
        # Make sure the actual branch is checked out when running on pull requests
        ref: ${{ github.head_ref }}
    - uses: creyD/action_autopep8@v3.1
